### ISSUE TITLE
"Not yet" loop issue

### ISSUE THREAD

**Issue by b3zi** [bruno222/whatsapp-web-bot#10]
Somehow you got a bug (or feature?!) with your not yet thingy in Line 67
Maybe you should try to redo it in another way because this one is little too unstable.
It also is a little to high frequent.

I will try to find some different solution...

I also added in my code
`if (lastMsg.toUpperCase().indexOf('@PING') != -1)/* I would recommend using NOT*/
            sendText = 'PONG'`

**Comment by vitalis110994** [comment]
If you add that code does it get read of the not yet loop issue?

**Comment by NelsonGaldeman** [comment]
Sometimes the contact name is not updated in chat-title element and the loop keeps going and going... I will try to fix it later.

**Comment by NelsonGaldeman** [comment]
Check the last pull request.
https://github.com/bruno222/whatsapp-web-bot/pull/12

**Comment by NelsonGaldeman** [comment]
I will keep you updated on this issue https://github.com/bruno222/whatsapp-web-bot/issues/8
