### ISSUE TITLE
whatsapp-web-bot not working with Whatsapp Business account

### ISSUE THREAD

**Issue by stefano71** [bruno222/whatsapp-web-bot#100]
Hello bruno22,

I tried your whatsapp-web-bot but it only works with the personal account,
unfortunately it does not work with the whatsapp business account.

do you have any idea why this happens.

**Comment by NelsonGaldeman** [comment]
It happens because it was meant for personal accounts only.

**Comment by stefano71** [comment]
you have a solution also paying?
