### ISSUE TITLE
whatsapp-web-bot not working with account business

### ISSUE THREAD

**Issue by stefano71** [bruno222/whatsapp-web-bot#101]
I'm trying your whatsapp-web-bot script but unfortunately it doesn't work with the whatsapp business account. Do you have any solution? Also paying.

**Comment by NelsonGaldeman** [comment]
Please stop spamming the issue section with this. You have already posted it and also commented some other issues spamming your problem. This is not a forum.

**Comment by stefano71** [comment]
Hi Nelson,

sorry if I insisted
you could also help me by paying to have this your business whatsapp script

I'm waiting for your answer

Stefano

**Comment by NelsonGaldeman** [comment]
I don't have time to help you. Sorry.
