### ISSUE TITLE
Some Issues when i running script

### ISSUE THREAD

**Issue by Rizky35** [bruno222/whatsapp-web-bot#109]
I have issues, when my friend send @HELP message, 
![error bot](https://user-images.githubusercontent.com/62740927/77734014-76b1cf80-703a-11ea-8cb7-aa2c700b1810.png)

**Comment by xlabour** [comment]
same here

**Comment by saama143** [comment]
find this line `messageBox = document.querySelectorAll("[contenteditable='true']")[0];`
and replace with  `messageBox = document.querySelectorAll("[contenteditable='true']")[1];`

**Comment by bruno222** [comment]
Just merged the opened PR. Should be working now.
