### ISSUE TITLE
Bot not Responding to Groups

### ISSUE THREAD

**Issue by AnimeLove** [bruno222/whatsapp-web-bot#11]
The Bot responds to my second number every time so why doenst he in my test group?

**Comment by vitalis110994** [comment]
Can you past your code

**Comment by NelsonGaldeman** [comment]
It should work for groups too. Could you post browser console output when you get a group message?

**Comment by NelsonGaldeman** [comment]
Did some tests and I found a bug related to groups. Fixed here https://github.com/bruno222/whatsapp-web-bot/pull/16
