### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by msaulohenrique** [bruno222/whatsapp-web-bot#111]
Hello everyone,

I tried to implement some functions in jquery to read from external json, but without success.
I found this project to be used on tampermonkey.net:
https://greasyfork.org/pt-BR/scripts/20990-whatsapp-web-chat-bot/code
It has well implemented the functions of collecting arguments and inserting json information that I want, however, the system is out of date in relation to the current version of WhatApp Web.
My knowledge of javascript is horrible. can you help me?

**Comment by Logicbloke** [comment]
Only post issues related to the project. Thanks!
