### ISSUE TITLE
How can I simulate a click on Whatsapp Web?

### ISSUE THREAD

**Issue by Cassiro** [bruno222/whatsapp-web-bot#19]
I'm practicing with your code. I want to go through the last 10 conversions and get the last 10 conversations.

I can not simulate a click on the conversions to open the conversation.

You code is amazing! 
thank you

**Comment by NelsonGaldeman** [comment]
This is what does the magic:

https://github.com/bruno222/whatsapp-web-bot/blob/master/bot.js#L99

First param: the element object you want to click on.
Second param: Should be "mousedown".

**Comment by pauloboc** [comment]
But if the browser is minimized or selected another tab?

**Comment by Cassiro** [comment]
Thank you!! it´s perfect

**Comment by NelsonGaldeman** [comment]
@pauloboc It also works if browser is minimized.
