### ISSUE TITLE
Handling Choices.

### ISSUE THREAD

**Issue by RogthatSinatra** [bruno222/whatsapp-web-bot#21]
Hey Am working on something for my School.
I was wondering how i could handle choices in situation like one below
User: @jokes
Me: choose type of jokes
      1.Explicit
      2.Normal
User: 1    //how can i catch this 
Me: An Explicit Joke.

**Comment by NelsonGaldeman** [comment]
There is a function to get the last received message from the active chat.
https://github.com/bruno222/whatsapp-web-bot/blob/master/bot.js#L55

**Comment by RogthatSinatra** [comment]
Thanks.
