### ISSUE TITLE
Not Working...

### ISSUE THREAD

**Issue by iskenderalpsakarya** [bruno222/whatsapp-web-bot#22]
it's not working right now. can you update ?

**Comment by Julian1104** [comment]
No work!

**Comment by NelsonGaldeman** [comment]
It seems that WhatsApp obfuscated class names because of this kind of bots... I will check if I can do something later.

![imagen](https://user-images.githubusercontent.com/9610178/36220693-51a76e26-119a-11e8-9fb6-07aba222bbaa.png)

**Comment by Julian1104** [comment]
i change code line u said, but dont work!

**Comment by iskenderalpsakarya** [comment]
Julian,

i change code line and working. but only unread message counter working.

**Comment by Julian1104** [comment]
its possible u share code with me?.... because in my browser dont run!

**Comment by iskenderalpsakarya** [comment]
//i changed only this lines
_____________________________________________________________
//Click at Send Button
		eventFire(document.querySelector('#main span[data-icon="send"]'), 'click');

		cb();
_____________________________________________________________
//and....this lines
//
	// MAIN LOGIC
	//
	const start = (_chats, cnt = 0) => {
		// get next unread chat
		const chats = _chats || document.querySelectorAll('._15G96');
		const chat = chats[cnt];

//That's all. I'm not very knowledgeable about JS. But I can get all the class names. I don't know where to //write it :) don't forget. Only the counter of messages is running correctly there is nothing else working.

**Comment by iskenderalpsakarya** [comment]
Hello. The current classes are here. I wonder if you can update it accordingly.

https://github.com/MagicLegend/WhatsappTheme/blob/master/fs-whatsapp.js

**Comment by preetishkakkar** [comment]
Hello, 
I fixed the issues because of new obfuscated whatsapp css classes. Cheked in my fork https://github.com/preetishkakkar/whatsapp-web-bot/blob/master/bot.js (https://github.com/preetishkakkar/whatsapp-web-bot/commit/6167b5d7a33f01a3820803d3bd8186c79a562a2a) , but feel free to use/integrate. I am worried sooner or later these might change as well.

**Comment by preetishkakkar** [comment]
Another minor change (https://github.com/preetishkakkar/whatsapp-web-bot/commit/ea1f593fd051f16f55c22a480257b4b7905940d9#diff-9d199097bf1be7e582b7cb3a378cfbf0)

**Comment by NelsonGaldeman** [comment]
@preetishkakkar please create a pull request and I will check it later.

**Comment by Patrique** [comment]
these classes will be changed from time to time, shit

**Comment by NelsonGaldeman** [comment]
@Patrique that's true. We don't know how they work so they may change and they will need periodic updates.

**Comment by bruno222** [comment]
This classes names are changed by React or Webpack on every built. Do it's better to avoid using them.

I thing a better approach for long term support is, instead of using classes, use the full html path, like 
`body div div div div h1` - something like that... If the html tags does not have an **id** value.

I know it's ugly, but at least the HTML structure will not be changed every build.

**Comment by Julian1104** [comment]
ITS NO WORKING AGAIN!

**Comment by preetishkakkar** [comment]
For me it is, you are probably doing something wrong

**Comment by preetishkakkar** [comment]
@bruno222 - Any ideas on how react creates this decoding? I also see they are using react but I have very limited knowledge of react, if we know how react encode/decode, then we may be able to use that to encode from known standard strings?

**Comment by bruno222** [comment]
Hi @preetishkakkar. I don't know much about React, but I know a little about Vue.js - they both work in the same way.

They use Webpack to compile tour beautiful code into a ugly bundle. At the compiling time, Webpack changes the classes names to reduce their names (there's other reasons on why the change the classes names, like allowing the same class name in different files).

So the software developer on Whatsapp does not see this ugly class name and it's not possible to create a rule to track/detect these ugly class name.

The safest way to reduce our code to be breaking every new version of whatsapp web, it is replacing the querySelector from class-names (#userName) to html-structure (body div div div div h1), once html structure does not modifies as much as class names.

**Comment by NelsonGaldeman** [comment]
But up to now we detect new messages because of an extra class name on a specific element. We need to find another way. Could be checking if the green unread tag is there... I need to do some tests.

**Comment by NelsonGaldeman** [comment]
I made a simple function to achieve Bruno's idea in a "beauty" way. An array where you can setup child positions from body to find an element. Then you simply call "getElement('chats')" and you get the node list of each chat.

This should be equivalent to "document.querySelectorAll('.chat')". I will try to finish the whole thing today.


	var elementConfig = {
		"chats": [1, 0, 5, 2, 0, 3, 0, 0, 0]
	};
	function getElement(id){
		if (!elementConfig[id]){
			return -2;
		}
		var elem = document.body;
		var elementArr = elementConfig[id];
		for (var x in elementArr){
			var pos = elementArr[x];
			if (isNaN(pos*1)){
				continue;
			}
			if (!elem.childNodes[pos]){
				return -1;
			}
			elem = elem.childNodes[pos];
		}
		return elem;
	}

**Comment by bruno222** [comment]
Wow, awesome, Nelson!

Suck that, Zuckerberg!

**Comment by NelsonGaldeman** [comment]
We still need to solve how to get unread chats. I didn't look at it yet, but I can hear ideas :P

**Comment by bruno222** [comment]
I've blocked Julian1104 from this repo.

- He's new on github (he created his account 9 days ago)
- He's boring (asking us fix the code right away, like we were his employee)
- CAPS LOCK to often turned on.

Maintenance is everything.

**Comment by Patrique** [comment]
Unread conversations are fundamental, I do not even know where to start, I'll be waiting for news: D

**Comment by preetishkakkar** [comment]
I may have sometime later to look into it, check it in and I will see if I can spend some time.

**Comment by NelsonGaldeman** [comment]
If someone wants to help, check the last commit https://github.com/bruno222/whatsapp-web-bot/commit/827b6fde19977507567693f530a21c44629cb957

**Comment by preetishkakkar** [comment]
Hey Nelson, I have fixed SelectChat & sendMessage, created a pull request/review for you, feel free to merge.

**Comment by RogthatSinatra** [comment]
Great its working again. [preetishkakkar](https://github.com/preetishkakkar)

**Comment by NelsonGaldeman** [comment]
Great work @preetishkakkar ! I will check it as soon as I get rid of some tasks. Hope I can do it today.

**Comment by NelsonGaldeman** [comment]
Finally the whole bot fixed and working again https://github.com/bruno222/whatsapp-web-bot/pull/26

We still have 2 minor known bugs. I will fix them later.

**Comment by heitorcaldeira** [comment]
Nice work bruno :) I didn't know how to start, now I have a good base xD
