### ISSUE TITLE
No longer litsens to messages.

### ISSUE THREAD

**Issue by RogthatSinatra** [bruno222/whatsapp-web-bot#24]
New messages cannot be read.
console only shows nothing to do.

**Comment by valenti1234** [comment]
same problem here, whatsapp release a new version that cheange everything

**Comment by Julian1104** [comment]
no work!

**Comment by NelsonGaldeman** [comment]
It seems that WhatsApp obfuscated class names because of this kind of bots... I will check if I can do something later.

![imagen](https://user-images.githubusercontent.com/9610178/36220551-c6f09a28-1199-11e8-88d3-2af4c4435e50.png)

**Comment by NelsonGaldeman** [comment]
Duplicate of https://github.com/bruno222/whatsapp-web-bot/issues/22
