### ISSUE TITLE
Chat icons

### ISSUE THREAD

**Issue by NelsonGaldeman** [bruno222/whatsapp-web-bot#28]
Do you know any other icon than "new messages", "muted" and "pinned"? I can't remember any more. The point is that if there is any other icon that could appear the function "getUnreadChats" will not work properly.

![imagen](https://user-images.githubusercontent.com/9610178/36735385-db892db8-1bb4-11e8-93c7-9c1e7ae49db7.png)

**Comment by bruno222** [comment]
I am looking here, I think that's it, Nelson. Nothing else I do believe.

**Comment by NelsonGaldeman** [comment]
I've just pushed a new commit adding "pinned" icon to the function. I will leave this open.
