### ISSUE TITLE
Ajuda-BR

### ISSUE THREAD

**Issue by monteirosk** [bruno222/whatsapp-web-bot#3]
Estou na mesma situação usava o yowsup mas peguei ban no meu chatbot, estou procurando alternativas o seu js Não funcionou comigo...

monteiro.william4@gmail.com

![captura de tela 2017-10-02 as 10 22 11](https://user-images.githubusercontent.com/1817334/31082042-c2987f16-a75b-11e7-9892-12b2982ae660.png)

**Comment by bruno222** [comment]
Oi Monteiro. Td certo?

O Bot só lê as mensagens dos chats que não estão selecionados. Então:

1. Ai no chatsappweb, clica em Aline (só pra sair da tela do William)
2. pelo celular do William, envia @HELP.

Daí vai funcionar. Fiz este demo pro bot pra não responder qdo a tela estiver ativa no usuário.

Esse código é mais um prova de conceito... Não vais conseguir fazer um Bot legal usando esse código. Use esse código pra teres um Norte de como fazer um Bot de verdade... Porque com certeza dá pra fazer, e não serás banido.

Valeu!

**Comment by monteirosk** [comment]
Obrigado por responder

**Comment by bruno222** [comment]
imagina. qquer dúvida só chamar! :) valeu amigo. abs
