### ISSUE TITLE
@HELP bug if chat is open

### ISSUE THREAD

**Issue by NelsonGaldeman** [bruno222/whatsapp-web-bot#30]
I've fixed it in the past but It happens again after new WPW release. Didn't check it yet.

If your friend sends @HELP command and his chat is active, you will also get a response from @JOKE command. It's also processing sent messages and it should process received ones only.

**Comment by mauriciog98** [comment]
It happens because the bot does not ignore the last message sent when chat is open, to avoid this change the code like this:
`````
if (lastMsg.toUpperCase().indexOf('@JOKE') > -1 && lastMsg.trim().length < 6){
      sendText = jokeList[rand(jokeList.length - 1)];
}
`````
This must be done for all commands.

**Comment by NelsonGaldeman** [comment]
Could you create a PR please?
