### ISSUE TITLE
How can I send picture?

### ISSUE THREAD

**Issue by jakamoo33** [bruno222/whatsapp-web-bot#31]
How can I send picture?

whatsapp  web api
https://github.com/meik1710/WhatsApp-Web-API-

and send mesage code,
https://github.com/duzaq/whatsapp-web/blob/master/store.js

	X_makeSend = function(numero,mensagem){console.log('Send ... ',numero);
		setTimeout(() => {			 
					X_sendMessage(numero, mensagem);
					setTimeout( () => {
						Store.Wap.resyncMessages([ numero + "@c.us" ]);
					}, 1500);
				}, 500);
	}

	/////////////////
	X_sendMessage = function(to = null, body = null) {
		if (to == null || body == null) return {
			'status': 401,
			'status_msg': "Invalid user or body text"
		}
		var id = X_makeID();
		var msg = Store.Msg.models[0];
		msg.id.id = id;
		msg.id.remote = to + "@c.us";
		msg.type = "chat";
		msg.body = body;
		msg.to = to + "@c.us";
		msg.t = Math.ceil(new Date().getTime() / 1000);
		Store.Msg.send(msg);
	};

	X_makeID = function() {
		var text = "";
		var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
		for (var i = 0; i < 20; i++) text += possible.charAt(Math.floor(Math.random() * possible.length));
		return text;
	};
	X_makeSend(553399999999,'teste');

**Comment by NelsonGaldeman** [comment]
Nice repo! We could use some stuff from there :)

**Comment by Patrique** [comment]
Nice!!!

**Comment by NelsonGaldeman** [comment]
I wonder if using internal WPW functions makes us an easy target for bans hmm... yeah is still "client side", but they could add some test to detect a strange behaviour. Suckerberga has some tricks under his sleeve.

Working from DOM is definitely the safest way to go.

**Comment by NelsonGaldeman** [comment]
@bruno222 what do you think about my last comment?

**Comment by bruno222** [comment]
I agree with you that DOM is safest, but WPW functions is still OK to go, and I think it would be easy to maintain the project using WPW functions. I could pick the WPW functions if it is easy to do the reverse engineering (I did not take a look into it)

The most important thing it is to not communicate directly with back-end APIs (like yowsup does). I don't think the Suckerberga will make extra functions to detect us.. Only we have 10 thousand stars, perhaps - hehe.

**Comment by phpRajat** [comment]
This code working for send media [https://gist.github.com/phpRajat/a6422922efae32914f4dbd1082f3f412](https://gist.github.com/phpRajat/a6422922efae32914f4dbd1082f3f412)

**Comment by NelsonGaldeman** [comment]
Well done! I may add it as an example function since many people've asked for it. Feel free to create a PR if you want to do it.
