### ISSUE TITLE
Hi,Not able to change value of search input box via javascript.

### ISSUE THREAD

**Issue by adarsh431** [bruno222/whatsapp-web-bot#32]
Hi,
Thanks for the great work. Have added a function to search user and send message but changing the value of input box is not triggering the search call.
Any help will be appreciated. 

        const searchContact = (title, message, cb) => {
        //add text into input field
        var input = document.querySelector('#input-chatlist-search');
        eventFire(input, 'focus');
        input.value = title.replace(/  /gm, '')

        //Force refresh
        event = document.createEvent("UIEvents");
        event.initUIEvent("input", true, true, window, 1)
        document.querySelector('#input-chatlist-search').dispatchEvent(event)

        setTimeout(() => {
            chats = document.querySelectorAll('._2wP_Y')
            if (chats != []) {
                var contactFound = false;
                for (var i = 0; i < chats.length; i++) {
                    var chat = chats[i];
                    var chatTitle = chat.querySelector('._25Ooe > span').title;
                    if (chatTitle == title) {
                        selectChat(chat, () => {
                            sendMessage(chat, message.trim(), () => {
                                console.log("Message sent: ", message)
                            })
                        })
                        contactFound = true;
                        break;
                    }
                }

                if (!contactFound) {
                    console.error("Contact not found: ", title);
                    NOT_FOUND.push(title);
                }
            } else {
                console.error("Contact not found: ", title);
                NOT_FOUND.push(title);
            }
        }, 3000);

        cb()
    }

**Comment by NelsonGaldeman** [comment]
I didn't check the whole code, but do not use obfuscated classes on "querySelector" method because they will change every time WhatsApp releases an update. Check out the "getElement" function and ask any questions about it.

About your question, why do you need to find a contact from search? I may advice you a better solution.

**Comment by adarsh431** [comment]
the use case is to read name from array of objects and search the name and send them a message.
searching linearly for every name didn't seen efficient.
data=[{name:"Adarsh", message:"loren ipsum"}]

**Comment by NelsonGaldeman** [comment]
I will try to play around with your code tomorrow.

**Comment by adarsh431** [comment]
any updates?

**Comment by NelsonGaldeman** [comment]
I didn't have time to check it. I will do it as soon as possible.

**Comment by adarsh431** [comment]
Hi Nelson, sorry to bother you man.
I was was trying to simulate the js events to trigger the search. 
"search":[1, 0, 5, 2, 0, 2, 0, 3, 0]
this is the array needed for getElement function. But once you get the <input> element. I am not able to trigger the search after changing its value.
Would really appreciate if you could look into this.

**Comment by NelsonGaldeman** [comment]
I promise to check it at night!

**Comment by NelsonGaldeman** [comment]
I've been trying to simulate a keyboard input in many ways, using different libraries that works on any input but I couldn't make it work on WPW. Will keep playing to get it work.

**Comment by NelsonGaldeman** [comment]
Couldn't do it. If someone finds a solution, feel free to reopen the issue.
