### ISSUE TITLE
our phone number is banned from using WhatsApp. Contact support for help.

### ISSUE THREAD

**Issue by jerryrat** [bruno222/whatsapp-web-bot#33]
your phone number is banned from using WhatsApp. Contact support for help.

after use this

so **PLZ DO NOT USE THIS JS**

**Comment by bruno222** [comment]
Even if you use the official Whatsapp App in your Android, you can get banned. 

Sending a lot of messages to a lot of people will trigger the users to click in "this message is a spam", which  you eventually will get banned, even if you use the official Whatsapp App.

Soooo, the questions now is:

- What was you doing? What is your service? 
- Who starts the conversation (you or the user)?
- How many messages per hour or per day were you sending?
- What is the content of the messages?

Replying this I will surely know if it was a problem with your solution (most likely) or if Whatsapp has rules to detect Bot on WhatsApp Web (which I really don't believe it)

Bruno

**Comment by Patrique** [comment]
I find it very difficult that it was because of this git, because the person who starts the conversation is the user, depends a lot on the way it is being applied, as Bruno has listed.

**Comment by NelsonGaldeman** [comment]
In addition to @bruno222's questions, did you try any other bot with the same number? Usually, bans are not triggered immediately.

**Comment by jerryrat** [comment]
@bruno222 
What was you doing? What is your service?

nothing but test this JS to another ID

Who starts the conversation (you or the user)?

Both ID test

How many messages per hour or per day were you sending?

very less. 

What is the content of the messages?

just this demo JS

-------------------

updating, banned 3days  and  support no reply 

**and I use the official app for IOS not Android**

**Comment by jerryrat** [comment]
@NelsonGaldeman no, only this JS.

and it works not well in my chrome, it will auto reply toooo many times, more than 10 times after **@help or @time or @joke**

and I test on 9th March, but banned on 19th....

**Comment by NelsonGaldeman** [comment]
If both (you and the user) starts the conversation, you were not using the default code. Could you post your own source?

**Comment by jerryrat** [comment]
@NelsonGaldeman I have 2 numbers and I test one with another

**Comment by bruno222** [comment]
Perhaps this issue below trigged the anti-spam rule at the Whatsapp side:

"reply toooo many times, more than 10 times"

Well, let see if it happens again, if whatsapp blocks more people that was using our code.

It is just too hard to make assumptions at this point. Right now, IMO, it seems odd that WhatsApp could have detected our source code as a Bot and banned it. Possible, but odd.
