### ISSUE TITLE
Uncaught TypeError when chat is open

### ISSUE THREAD

**Issue by nitroinhidro** [bruno222/whatsapp-web-bot#34]
Wed Mar 21 2018 14:59:59 GMT-0500 (Central Daylight Time) "new message to process, uhull -> " "raj" "Yazan:
@time
"
VM788:178 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
    at sendMessage (<anonymous>:178:24)
    at selectChat (<anonymous>:266:5)
    at setTimeout (<anonymous>:156:12)

`//add text into input field
		messageBox.innerHTML = message.replace(/  /gm,'');`

When I highlight the error this is what I get:
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

**Comment by NelsonGaldeman** [comment]
Please open any chat and paste this in the console

	document.querySelectorAll("[spellcheck='true']")[0]

Please post the output.

**Comment by nitroinhidro** [comment]
`document.querySelectorAll("[spellcheck='true']")[0]
undefined`

**Comment by NelsonGaldeman** [comment]
Which browser are you using?

I got this output from Firefox & Chrome
![imagen](https://user-images.githubusercontent.com/9610178/37736179-f6d5c208-2d2e-11e8-80c2-a65f95eeb49c.png)

**Comment by nitroinhidro** [comment]
![whatsapp](https://user-images.githubusercontent.com/30022683/37736401-cf757c04-2d1e-11e8-86d0-61b7c1e2bb6c.PNG)

Google Chrome is up to date
Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by NelsonGaldeman** [comment]
Try with this

document.querySelectorAll("[contenteditable='true']")[0]

**Comment by nitroinhidro** [comment]
![whatsapp](https://user-images.githubusercontent.com/30022683/37736736-ae0a7546-2d1f-11e8-9202-a1cf5ec0395a.PNG)

I got Something

**Comment by NelsonGaldeman** [comment]
Replace it on the source and it will work.

**Comment by 16564017** [comment]
After applying @NelsonGaldeman 's solution i.e. changed
 
`messageBox.innerHTML = message.replace(/ /gm,'');`
to
`messageBox = document.querySelectorAll("[contenteditable='true']")[0];`

the bot sends `[object HTMLDivElement]` to the user and stops after 2 messages, raises Uncaught TypeError
at `el.dispatchEvent(evt);`

**Comment by NelsonGaldeman** [comment]
You replaced the wrong line.

Just replace this

    document.querySelectorAll("[spellcheck='true']")[0]

With

    document.querySelectorAll("[contenteditable='true']")[0]

**Comment by NelsonGaldeman** [comment]
I've just uploaded it to the repository, just sync yours.
