### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ! on line 262.

### ISSUE THREAD

**Issue by agustinx19** [bruno222/whatsapp-web-bot#35]
**VM883:262 Uncaught SyntaxError: Unexpected token !**

                // select chat and send message
		var send = { sendMessage(!processLastMsgOnChat ? chat : null, sendText.trim(), () => {
				goAgain(() => { start(chats, cnt + 1) }, 0.1);
			});
		};

**Comment by agustinx19** [comment]
chrome, last ver

**Comment by NelsonGaldeman** [comment]
Confirmed bug. I've just pushed a commit with the fix. Feel free to re-open the issue if you have any problems.
