### ISSUE TITLE
Get sender name?

### ISSUE THREAD

**Issue by rzfzr** [bruno222/whatsapp-web-bot#38]
Hello there,
the bot works great, however how can I get name of the sender instead of the title? So that I can handle messages from different people in the group instead of the "Hello the name of the group."
I figure it can be done by adding another elementConfig, I used some trial and error but didn't manage it, is there a way to see the page elements in a hierarchy to make it easy to visualize it?

**Comment by NelsonGaldeman** [comment]
That would only be possible if the chat is open I guess. (Just guessing based on experience). Let me check it.

**Comment by rzfzr** [comment]
![image](https://user-images.githubusercontent.com/13456224/38260943-48b2d39e-373f-11e8-9651-0d045cd15825.png)
It is visible even if not selected

**Comment by NelsonGaldeman** [comment]
You are right, I didn't remember that. Give me some minutes.

**Comment by NelsonGaldeman** [comment]
For you to know, "getElement" & "getUnreadChats" were not modified. But I added "chat_lastname" value to elementConfig array.

If you run the following script it will return the last message name OR contact name if it is not a group.

	var elementConfig = {
		"chats": [1, 0, 5, 2, 0, 3, 0, 0, 0],
		"chat_icons": [0, 0, 1, 1, 1, 0],
		"chat_title": [0, 0, 1, 0, 0, 0],
		"chat_lastmsg": [0, 0, 1, 1, 0, 0],
		"chat_active": [0, 0],
		"selected_title": [1, 0, 5, 3, 0, 1, 1, 0, 0, 0],
		"chat_lastname": [0, 0, 1, 1, 0, 0, 0, 0]
	};

	function getElement(id, parent){
		if (!elementConfig[id]){
			return false;
		}
		var elem = !parent ? document.body : parent;
		var elementArr = elementConfig[id];
		for (var x in elementArr){
			var pos = elementArr[x];
			if (isNaN(pos*1)){ //dont know why, but for some reason after the last position it loops once again and "pos" is loaded with a function WTF. I got tired finding why and did this
				continue;
			}
			if (!elem.childNodes[pos]){
				return false;
			}
			elem = elem.childNodes[pos];
		}
		return elem;
	}

	function getUnreadChats(){
		var unreadchats = [];
		var chats = getElement("chats");
		if (chats){
			chats = chats.childNodes;
			for (var i in chats){
				if (!(chats[i] instanceof Element)){
					continue;
				}
				var icons = getElement("chat_icons", chats[i]).childNodes;
				if (!icons){
					continue;
				}
				for (var j in icons){
					if (icons[j] instanceof Element){
						if (!(icons[j].childNodes[0].getAttribute('data-icon') == 'muted' || icons[j].childNodes[0].getAttribute('data-icon') == 'pinned')){
							unreadchats.push(chats[i]);
							break;
						}
					}
				}
			}
		}
		return unreadchats;
	}

	var chat = getUnreadChats()[1];
	lastName = (getElement("chat_lastname", chat) || { innerText: '' }).innerText;
	if (!lastName){
		lastName = getElement("chat_title",chat).title;
	}
	console.log(lastName);

**Comment by rzfzr** [comment]
Great stuff, I'll check it out today,
Thanks man

**Comment by NelsonGaldeman** [comment]
Feel free to re-open the issue if you have any questions or need further help.

**Comment by stefano71** [comment]
Hello Nelson,
how to get the values of elementConfig
