### ISSUE TITLE
How to display "Is typing" message in WhatsApp

### ISSUE THREAD

**Issue by ajzuse** [bruno222/whatsapp-web-bot#43]
Is possible display "is typing" to receivers using the bot?

I question that because if is possible, is a try to not block the number, simulating the typing action to the receivers. I try but don't have success in display the "is typing" status to receivers.

Thanks for advance.

**Comment by NelsonGaldeman** [comment]
Maybe an algorithm to write the message letter by letter. Like 0.1-0.2 secs each letter and calling "change" event of the input could make the trick. Try it and tell us.
