### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by mauriciog98** [bruno222/whatsapp-web-bot#46]
It tells me in console "not yet" and when debugging, the chat variable in the constant selectchat is not defined

**Comment by NelsonGaldeman** [comment]
We'll check it out.

**Comment by mauriciog98** [comment]
Hi, i find the error. I don't know how you find the element with elementConfig, but I find the error, the element selected_tittle has change, i has find it with one unique difference
```
const selectChat = (chat, cb) => {
		const title = getElement("chat_title",chat).title;
		eventFire(chat.firstChild.firstChild, 'mousedown');
		if (!cb) return;
		const loopFewTimes = () => {
			setTimeout(() => {
				const titleMain = getElement("selected_title").firstChild.title;
				if (titleMain !== undefined && titleMain != title){
					console.log('not yet');
					return loopFewTimes();
				}
				return cb();
			}, 300);
		}

		loopFewTimes();
	}

**Comment by NelsonGaldeman** [comment]
If adding "firstChild" solves the problem then you only need to add an extra "0" element to "selected_title" row of "elementConfig" array.

elementConfig contains the child indexes needed to get the element you want. It could be relative from any element or absolute (from body). For example "0, 2, 4" would be the fifth child of the third child of the first child of body or the second parameter element.

Feel free to create a pull request with the update.
