### ISSUE TITLE
Code for Command

### ISSUE THREAD

**Issue by AndreSpecker** [bruno222/whatsapp-web-bot#51]
Hello, someone would have a code for the bot to do the function:

When someone typed @INFO TEST, he would send a link www.link.com/TEST

@INFO TEST2 --> www.link.com/TEST2
@INFO TEST3 --> www.link.com/TEST3
...

Changing only the end of the link, with what the user type.

Thanks!!

**Comment by mauriciog98** [comment]
Use the existing string methods in javascript and verify that the beginning of the message is the command, in the base code verified that the command exists in the message
````
 if (lastMsg.trim().toUpperCase().indexOf('@INFO') == 0 ) {
            var path = lastMsg.trim().toUpperCase().split(' ')[1];
            sendText = "www.link.com/"+path;
    }
