### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by vscorpio** [bruno222/whatsapp-web-bot#52]
Hello guys!
I just took a look over your code and played a bit with it and I think it has great potential. I'm currently on a group with over 200 members which needs active moderation. I'd like a few functions but I'm completly garbage at js and I can't understand any piece of the code since I don't know js.

1. Commands to be processed when I send them not somebody else.
2. To be able to kick someone with text command
3. To be able to add someone in a group with a text command

I could really use this and I'd be very greatful if you can implement these 3 features.

Thanks a lot!

Keep on the good work!

**Comment by mauriciog98** [comment]
I consider that these commands are not possible, it would be easier and more effective to develop an app that goes directly to the WhatsApp server and takes control of the account, but is risking being banned. Another possibility is an app that takes control of WhatsApp from Android. In js it is very difficult, you would develop an extensive code that when leaving updates would become repetitive and inefficient or you should change too much, almost completely. The best thing is that you look for a project that goes directly to the server

**Comment by vscorpio** [comment]
Alright! Thanks for the info.
