### ISSUE TITLE
Search in .json file

### ISSUE THREAD

**Issue by AndreSpecker** [bruno222/whatsapp-web-bot#53]
Hello, someone would have an example of an "@ITEM Apple" where they would search on a link.com/file.json and would send the data if the searched item is found.

Thanks again :D

**Comment by mauriciog98** [comment]
Hi, it's impossible do it in the console, maybe you could create a input type file, upload the local JSON file here and read by javascript, but it's more practice make an array and search in it

**Comment by ctoveloz** [comment]
I have the same question, I wanted to know if have possibility an RSS feed in XML and send the title with the link to the group when you have a new item.
