### ISSUE TITLE
hOLA alguna idea de como conectar WhatsAPP Web a mysql es decir que los mensaje se guarden hay  ?

### ISSUE THREAD

**Issue by Albert947** [bruno222/whatsapp-web-bot#54]

**Comment by mauriciog98** [comment]
Hola, primero tienes que lidiar con una conexión a MySQL a través de PHP que te permita peticiones (requests) desde direcciones diferentes a la local y después hacer que las peticiones que envias desde la consola se envíen a nombre de la página whatsapp.com y no como un conmando externo de consola, lo cual se logra empaquetando el código como una extensión para un navegador web, pero esto cambia entre cada navegador.

**Comment by NelsonGaldeman** [comment]
@mauriciog98 no hace falta una extensión, podés enviar peticiones a cualquier sitio por AJAX si habilitás los "cross-origin requests" en el navegador.

**Comment by uokivan** [comment]
tiene alguna muestra?

**Comment by Albert947** [comment]
no, no tengo ninguna muestra..............................................................


________________________________
De: uokivan <notifications@github.com>
Enviado: jueves, 9 de agosto de 2018 1:03
Para: bruno222/whatsapp-web-bot
Cc: Albert947; Author
Asunto: Re: [bruno222/whatsapp-web-bot] hOLA alguna idea de como conectar WhatsAPP Web a mysql es decir que los mensaje se guarden hay ? (#54)


tiene alguna muestra?
