### ISSUE TITLE
when I use the bot.js

### ISSUE THREAD

**Issue by uokivan** [bruno222/whatsapp-web-bot#55]
I use the bot.js,
when I send "@help"

the whatsapp can show"

Cool ${title}! Some commands that you can send me:
				1. *@TIME*
				2. *@JOKE*

**********************************************

but after that, whatsapp also show me the joke, such as : 
Husband and Wife had a Fight.
		Wife called Mom : He fought with me again,
		I am coming to you.
		Mom : No beta, he must pay for his mistake,
		I am comming to stay with U!

********************************************

How to stop it?

**Comment by mauriciog98** [comment]
#30  #48

**Comment by mauriciog98** [comment]
fixed in the last update
