### ISSUE TITLE
Puedo enviar un archivo desde mi computadora?

### ISSUE THREAD

**Issue by Bryan9314** [bruno222/whatsapp-web-bot#65]
Hola saludos desde Ecuador.

Me agrado mucho su trabajo.  Quería hacerles una consulta es posible enviar algún archivo de texto localizado en mi ordenador?

**Comment by NelsonGaldeman** [comment]
Poder se puede, pero no es sencillo. Hasta ahora los que hemos investigado un poco no lo hemos conseguido.

**Comment by Bryan9314** [comment]
Vale gracias
