### ISSUE TITLE
Latest WhatsApp API

### ISSUE THREAD

**Issue by letstalk1** [bruno222/whatsapp-web-bot#66]
Have You Checked Chat-API?
----------------
- Easy to Use
- One of the best API for WhatsApp with WA2.0 Protocol.
- Latest Android Environment
- All Required Functions and Features
- No More Blocking
- Sample Bot
- Well Documented
----------------
Try Now On

https://chat-api.net

**Comment by NelsonGaldeman** [comment]
The whole point of this proyect is to communicate with WhatsApp thought a bot without connecting directly to their servers (because of the high risk of being banned).
