### ISSUE TITLE
 How to identify if it's a group or private chat?

### ISSUE THREAD

**Issue by drksbr** [bruno222/whatsapp-web-bot#72]
Hello everyone, how do I identify if it is a group or if it is a private chat and how to capture the group name and user status?

**Comment by NelsonGaldeman** [comment]
If I have time, later I can show you some code on how to do it.

**Comment by imaginabit** [comment]
The only diference y see is group need to get title from this positions on elementConfig:
```
"chat_group_title": [0, 0, 1, 0, 0, 0],
"chat_title":       [0, 0, 1, 0, 0, 0, 0],
```
so 
if  (getElement("chat_title",chat).title === undefined) -> group

**Comment by NelsonGaldeman** [comment]
Yeap, that's a good workaround. I didn't test it but should work.
