### ISSUE TITLE
Sometimes the command is not recognized (Tested with FireFox Win7)

### ISSUE THREAD

**Issue by seizu** [bruno222/whatsapp-web-bot#73]
Sometimes the command is not recognized and there is even no console log, 
it seems that the message is completely missed.
![unbenannt](https://user-images.githubusercontent.com/1719149/48795007-f1a6ff80-ecfb-11e8-9533-3658f83685f1.PNG)

**Comment by NelsonGaldeman** [comment]
Are you using default source code?

It may be de browser that takes some time to send an answer. It should show some logs on the console... if you can't see anything, you have to change your console filters.

**Comment by seizu** [comment]
No problem with log outputs, if the command is recognized  I can see incoming and outgoing log messages. I will try to reproduce it and attach a screenshot with logs.

**Comment by seizu** [comment]
This time I've tested it with Firefox 64.0b12 64-Bit, same issue.
Screenshot: http://my.jetscreenshot.com/demo/20181124-o9gj-320kb.jpg

**Comment by NelsonGaldeman** [comment]
Could you link the image agiain? The link is broken.

**Comment by seizu** [comment]
![2018-11-29_18-39](https://user-images.githubusercontent.com/1719149/49240748-46d2c780-f406-11e8-8143-4f3dfea299bc.png)

**Comment by bruno222** [comment]
I am closing all the issues older then 2019. If the problem remains, please fell free to open a new issue.
