### ISSUE TITLE
Please, help to direct access to sendMessage function

### ISSUE THREAD

**Issue by CarlosAlbertoAr** [bruno222/whatsapp-web-bot#74]
Very good project, congratulations to the author.

Can someone help me how can I change the code to be able to directly use the sendMessage function.
I try and have following error: ReferenceError: sendMessage is not defined. It seems something like if it was inaccessible for direct use, I do not understand much about Java Script.

My pleasure is to make an app that when typing, automatically enter the username. Ex: #MyName Says: Hello!

Thank you.

**Comment by NelsonGaldeman** [comment]
Here you are. A standalone function you can use to send messages. It only works if you previously clicked on the chat manually.

	function sendMessage(message){
		var messageBox = document.querySelectorAll("[contenteditable='true']")[0];
		messageBox.innerHTML = message.replace(/  /gm,'');

		event = document.createEvent("UIEvents");
		event.initUIEvent("input", true, true, window, 1);
		messageBox.dispatchEvent(event);
		
		var evt = document.createEvent("MouseEvents");
		evt.initMouseEvent('click', true, true, window,0, 0, 0, 0, 0, false, false, false, false, 0, null);
		document.querySelector('span[data-icon="send"]').dispatchEvent(evt);
	};

Usage: sendMessage("MESSAGE HERE");

**Comment by CarlosAlbertoAr** [comment]
Thank you very much, my dear. Answer me what I want to do.
