### ISSUE TITLE
How to add a countdown to a certain date? 

### ISSUE THREAD

**Issue by smaybe** [bruno222/whatsapp-web-bot#76]
Hey, very cool bot! I have a question and because I am a total beginner I thought I'd ask for help :) 

I want to create a timer for a group with a bunch of friends that counts down to a certain time on a certain day. 
For example: I set christmas eve 17:00 as the desired date and whenever someone in the group writes "@countdown" the bot would write something like "its 24 days, 13 hours and 10 seconds till christmas eve." And maybe once or twice a day the bot would write that on its own without anyone writing @countdown. (I am thinking of maybe adding a nice message each day which could be random but this is not priority) 

Now because I am very unexperienced I am looking for help on how to implement that into the code :) I would really appreciate someone helping me out :) 
Thanks and have a nice day :)

**Comment by NelsonGaldeman** [comment]
I can say it's possible and also isn't very hard to acheive it. But I don't have time to help you. I'll leave this open in case someone wants to help you. I would advice you to ask at stackoverflow. You may find better help there.

**Comment by smaybe** [comment]
Okay I thought I'd update here: I added this to the main logic: 

		

> var d1 = new Date(); //"now"
> 		var d2 = new Date("2018/12/24 17:00:00")  // some date
> 		var diff = Math.abs(d1-d2)/1000;  // difference in seconds
> 		diff = Math.abs(Math.floor(diff));
> 		var days = Math.floor(diff/(24*60*60));
> 		var leftSec = diff - days * 24*60*60;
> 		var hrs = Math.floor(leftSec/(60*60));
> 		var leftSec = leftSec - hrs * 60*60;
> 		var min = Math.floor(leftSec/(60));
> 		var leftSec = leftSec - min * 60;

If I then use the variables days, hrs, min and leftsec in a message that should be sent, it will send the time that is left until then :) For example: 

> if (lastMsg.toUpperCase().indexOf('@TIME') > -1){
> 			sendText = `
> 				There are *${days} Days, ${hrs} Hours, ${min} Minutes and ${leftSec} Seconds* left until it is Christmas.`
maybe this is interesting for someone else. 

I still have a few other things where I am stuck. I want to make the bot send a message every day at  13:00, but only into a certain group. Is there a way to do this? Maybe schedule the function every day for that time and then make the bot search for a group chat with the name "XYZ" and sent the message? Is that possible? 
Should I open a new issue for that matter? 
Help is greatly appreciated :) thanks!

**Comment by NelsonGaldeman** [comment]
The only way I can think of is to run an a ticker (using setInterval, for example) and check the time on the callback.
