### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by AndreSpecker** [bruno222/whatsapp-web-bot#77]
stopped working? no longer running the commands.

**Comment by NelsonGaldeman** [comment]
I've just tested it on Firefox. It's working. Which browser are you using? Any errors?

**Comment by mauriciog98** [comment]
Maybe you're using Whatsapp business, the bot only works for a normal account of Whatsapp in Whatsapp web

**Comment by AndreSpecker** [comment]
I use chrome, I use the business account at 6 months and it always worked. i will try on Firefox

https://i.imgur.com/ontPTnu.png

https://i.imgur.com/0I5zYxE.png

**Comment by NelsonGaldeman** [comment]
Those "violation" alerts are "new" never heard about them. I should get further information about them. 

Let me know If you have the same issue on Firefox.

**Comment by AndreSpecker** [comment]
Same problems, dont show any error, but not working.

**Comment by NelsonGaldeman** [comment]
I will try to reproduce the error and check If I can fix it.

**Comment by RogthatSinatra** [comment]
Its a whatsapp business error still works on the normal one

**Comment by mochadwi** [comment]
any updates on this?

**Comment by ridingthebulls** [comment]
Nothing Happened. Did As Described in the readme. Simply copied the .js coding and pasted in Console (F12) got no reply. Am i doing It wrong or it already stopped working...???

**Comment by ridingthebulls** [comment]
please direct how to link an .xlsx (excel workbook stored on local drive) with this code. All I want is to search the incoming message from column A and reply to the sender the related data in column B if the msg is matched. Thanks.
