### ISSUE TITLE
How to communicate with server?

### ISSUE THREAD

**Issue by alam157** [bruno222/whatsapp-web-bot#78]
I want to get data from my server and then send a broadcast message by whatsapp. how i can do?

**Comment by NelsonGaldeman** [comment]
You must disable your browser cross-origin ajax request protection, then you can get whatever you want using AJAX. Finally, you can loop thought your chats and send the same message to everybody.

Sending the same message to a lot of contacts may flag your account as a spammer, probably ending on your account banned.

**Comment by alam157** [comment]
i had disable cross-origin ajax request i got error like this

> Refused to connect to 'http://domain.com/tes.php' because it violates the following Content Security Policy directive: "connect-src *.facebook.com facebook.com *.fbcdn.net *.facebook.net *.spotilocal.com:* wss://*.facebook.com:* https://fb.scanandcleanlocal.com:* attachment.fbsbx.com ws://localhost:* blob: *.cdninstagram.com 'self' chrome-extension://boadgeojelhgndaghljhdicfkmllpafd chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm https://*.whatsapp.net https://www.facebook.com https://*.giphy.com https://*.tenor.co https://crashlogs.whatsapp.net/wa_clb_data https://crashlogs.whatsapp.net/wa_fls_upload_check https://www.bingapis.com/api/v6/images/search wss://*.web.whatsapp.com wss://web.whatsapp.com https://dyn.web.whatsapp.com"

**Comment by iskenderalpsakarya** [comment]
If this request continues, I can help you. (for paid) - Freelance

**Comment by PrinceTirah** [comment]
var user_code = lastMsg;
			//var user_code = "1234KTM567";
			var user_id = user_code.replace(/[^0-9\.]+/g, "");
			console.log(user_id);
			var Res =   $.ajax({
		            type:'POST',
		            url:'http://localhost/trynos/getData.php',
		            dataType: "json",
		           // global: false,
		            async: false,
		            data:{user_id:user_id},
		            success:function(data){
		              // if(data.status == 'ok'){
		                   //console.log(data.result.name);
		                   ddata = data.responseJson;
		                   return data;
		              // }else{
		                    //$('.user-content').slideUp();
		                //   alert("User not found...");
		              // } 
		            }
		        }).responseText;

		  	 //console.log(Res);
		    var JSONObject = JSON.parse(Res);
		    const dbname = JSONObject["result"]["name"];
		    const dbbal = JSONObject["result"]["balance"];
		    console.log(Res);`


////////////////////////////////////////////////

php file 

<?php
header('Access-Control-Allow-Origin: *');`
