### ISSUE TITLE
Input and output message

### ISSUE THREAD

**Issue by bmbraga** [bruno222/whatsapp-web-bot#79]
I tried to fix more I'm not locating.
The script is ignoring the sent messages themselves, without seeing what they are saying, and picking up the typed word as an incoming message and duplicating the responses.
Keyword output messages are read and answered automatically.
Can you help me ?

**Comment by NelsonGaldeman** [comment]
Sorry but I couldn't understand your question.

**Comment by NelsonGaldeman** [comment]
I will check it out later

**Comment by bmbraga** [comment]
Hi, how are you? You can verify? Thankful.

**Comment by bmbraga** [comment]
Me salva Bruno por favor, travei nesse bug, estava deixando meu bot bem bacana, mais o erro esta fazendo com que ele responda a suas próprias mensagens.

**Comment by HarryStrong** [comment]
Hello. I can help you

**Comment by HarryStrong** [comment]
please discuss in f-re-ela-nc-er

**Comment by iskenderalpsakarya** [comment]
If this request continues, I can help you. (for paid)
