### ISSUE TITLE
does not work with a business account

### ISSUE THREAD

**Issue by Timz** [bruno222/whatsapp-web-bot#81]
Hi!  If you run the script with a business account, the following is displayed in the log:
Tue Apr 09 2019 18:13:45 GMT+0300 (Москва, стандартное время) "new message ignored -> " "" ""
VM101:251 Tue Apr 09 2019 18:13:45 GMT+0300 (Москва, стандартное время) "new message ignored -> " "" ""
VM101:251 Tue Apr 09 2019 18:13:45 GMT+0300 (Москва, стандартное время) "new message ignored -> " "" ""
VM101:251 Tue Apr 09 2019 18:13:45 GMT+0300 (Москва, стандартное время) "new message ignored -> " "" ""
VM101:251 Tue Apr 09 2019 18:13:45 GMT+0300 (Москва, стандартное время) "new message ignored -> " "" ""
VM101:251 Tue Apr 09 2019 18:13:45 GMT+0300 (Москва, стандартное время) "new message ignored -> " "" ""
VM101:210 Tue Apr 09 2019 18:13:46 GMT+0300 (Москва, стандартное время) "nothing to do now... (1)" 17 undefined

**Comment by AndreSpecker** [comment]
not work for me too :(

**Comment by NelsonGaldeman** [comment]
I've never test it on a business account. I don't know how to get one. If you can link me an easy way to set it up I can fix it.

**Comment by AndreSpecker** [comment]
https://www.whatsapp.com/business/

**Comment by mauriciog98** [comment]
Hi, just needs reindex the elementConfig

**Comment by bruno222** [comment]
Can we close this ticket here after your PR, @mauriciog98? 

It is now working on Business account? (By the way, this project was never meant to work on business accounts... but if it is works, great!)

**Comment by PsyBooty** [comment]
Work just test it and looks ok!

**Comment by mauriciog98** [comment]
It still does not work on Business account. Next week I'll open PR

**Comment by PsyBooty** [comment]
well for me work '-'

**Comment by ilusis-site** [comment]
I managed do fix the selection of titles and messages with the correct elementConfig Index.
These are the settings that worked for me.
	var elementConfig = {
		"chats": [0, 0, 5, 2, 0, 3, 0, 0, 0],
		"chat_icons": [0, 0, 1, 1, 1, 0, 1, 1],
		"chat_title": [0, 0, 0, 1, 0, 0, 0, 0],
		"chat_lastmsg": [0, 0, 0, 1, 1, 0, 0],
		"chat_active": [0, 0],
		"selected_title": [0, 0, 5, 3, 0, 1, 1, 0, 0, 0, 0, 1, 0]
	};

However the method that selects the chat still doesn't work. The message "Not Yet" is sent a lot of times.

**Comment by stefano71** [comment]
me too does not work on the business account
do you have a solution?
