### ISSUE TITLE
How to get phone number

### ISSUE THREAD

**Issue by PrinceTirah** [bruno222/whatsapp-web-bot#83]
im try to get the lastmsg phone number from this class id   class="_3LL06" please help

**Comment by NelsonGaldeman** [comment]
The phone number is not stored in the side-panel. You should "click" programatically your contacct's profile and then get the number. It'll be slow but It can be done. Btw, element class changes every WPW build, so you should avoid them.

**Comment by PrinceTirah** [comment]
i want the phone number of the selected chat and of last_msg .

**Comment by PrinceTirah** [comment]
> The phone number is not stored in the side-panel. You should "click" programatically your contacct's profile and then get the number. It'll be slow but It can be done. Btw, element class changes every WPW build, so you should avoid them.

i dont understand you at all, please explain.

**Comment by NelsonGaldeman** [comment]
You must know how the bot works first. If you don't, my explanation is useless.

**Comment by PrinceTirah** [comment]
i dont understand how the bot work cause im new to js and dom

**Comment by PrinceTirah** [comment]
> You must know how the bot works first. If you don't, my explanation is useless.

what im trying to do is get the number of the person who send @HI or @TIME or @JOKE and echo the number to console thats all...

**Comment by NelsonGaldeman** [comment]
You should learn js and dom usage first.

**Comment by PrinceTirah** [comment]
> You should learn js and dom usage first.

okay thanks i will....send me link or tutorials if you have... trynosmuch@gmail.com or whatsapp 263773112343
