### ISSUE TITLE
Greetings message

### ISSUE THREAD

**Issue by PsyBooty** [bruno222/whatsapp-web-bot#88]
Can we have a Greetings message? i know that whatsapp busness have one, but only work every 15days
so its possible to responde a msg to the user independent of what he send us? and if he sends a command we check to the response?

**Comment by mauriciog98** [comment]
Just add a default value to var sendText
at line 229
`let sendText = "Hi, this is a default message";`

**Comment by PsyBooty** [comment]
well that is a easy fix...

**Comment by mauriciog98** [comment]
Close the issue if that was useful for you
