### ISSUE TITLE
Can not send message

### ISSUE THREAD

**Issue by ivanmestre** [bruno222/whatsapp-web-bot#9]
Hi, I'm getting this error:

`Uncaught TypeError: Cannot set property 'innerHTML' of null
    at sendMessage (<anonymous>:86:67)
    at selectChat (<anonymous>:152:13)
    at setTimeout (<anonymous>:72:24)`

This is the line that triggers that error (it is inside the sendText function):

`document.querySelector('.pluggable-input-body').innerHTML = message.replace(/  /gm,'')`

This happens because the click event is not opening the conversation, so when it tries to send the message, it can not find the input field element. Anyone knows how to fix this?

**Comment by NelsonGaldeman** [comment]
I'm trying to fix it. A few days ago the "click" event was working like a charm, not it is not. Don't know why. I also tested with other browsers and it still doesn't work.

**Comment by NelsonGaldeman** [comment]
Duplicate from https://github.com/bruno222/whatsapp-web-bot/issues/8
