### ISSUE TITLE
Let's integrate the function send to users that are not in the contact list

### ISSUE THREAD

**Issue by belmezjaen2** [bruno222/whatsapp-web-bot#93]
I would like to send messages to contacts that are not in the list, like the Chrome extension Waboxapp does. I tried refreshing the url to web.whatsapp.com/send?phone=xxxxxxx but that refreshes the whole site.

What do you suggest? Without reloading the app?

**Comment by NelsonGaldeman** [comment]
It's not possible with a standalone JS.

**Comment by NelsonGaldeman** [comment]
WE can do anything. You can learn how to create a Chrome extension and do it. Or hire someone to do it for you.

**Comment by belmezjaen2** [comment]
Pls don't be so rude. With a Chrome extension, what must be done to achive it? Just going to the web.whatsapp.com/send?phone=xxxxxxx page needs time to load the app, so maybe sending the sockets directly from the javascript? What do you suggest?
