### ISSUE TITLE
getChats() dont work 

### ISSUE THREAD

**Issue by ayarrus** [bruno222/whatsapp-web-bot#98]
var lastMessageOnChat = false;
var ignoreLastMsg = {};
var elementConfig = {
	"chats": [0, 0, 5, 2, 0, 3, 0, 0, 0],
	"chat_icons": [0, 0, 1, 1, 1, 0],
	"chat_title": [0, 0, 1, 0, 0, 0, 0],
	"chat_lastmsg": [0, 0, 1, 1, 0, 0],
	"chat_active": [0, 0],
	"selected_title": [0, 0, 5, 3, 0, 1, 1, 0, 0, 0, 0]
};

function getElement(id, parent) {
	if (!elementConfig[id]) {
		return false;
	}
	var elem = !parent ? document.body : parent;
	var elementArr = elementConfig[id];
	elementArr.forEach(function(pos) {
		if (!elem.childNodes[pos]) {
			return false;
		}
		elem = elem.childNodes[pos];
	});
	return elem;
}

**function getChats() {
	var chats = getElement("chats");
	if (chats) {
		chats = chats.childNodes;
		for (var i in chats) {
			console.log(chats[i]);
		}
	}
	return chats;
}**

I have 30 chats, only get 15???

**Comment by NelsonGaldeman** [comment]
Hmmm 15 may be the ones that are loaded in the front end.
